postgres:
  # You can lock down the postgres-version to e.g. postgres:10-alpine
  image: postgres:alpine
  environment:
  - POSTGRES_USER=ttrss
  - POSTGRES_DB=ttrss
  # make a permanent store for the data and implement backups
  # volumes:
  # - ./data:/var/lib/postgresql/data
ttrss:
  build: .
  links:
  - postgres
  environment:
  - DB_HOST=postgres
  - DB_NAME=ttrss
  - DB_USER=ttrss
  - BASE_URL=http://localhost:8000/
nginx:
  image: nginx:stable-alpine
  links:
  - ttrss
  volumes_from:
  - ttrss
  volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
  - 8000:80
